# plex-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: plex
  
  # This section points directly to the Helm repository
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: 1.1.1
    
    # All of our custom values are embedded here
    helm:
      values: |
        image:
          tag: plexpass

        timezone: "Asia/Jerusalem"

        service:
          type: NodePort
          port: 32400

        persistence:
          config:
            enabled: true
            storageClass: "local-path"
            accessMode: ReadWriteOnce
            size: 15Gi

          transcode:
            enabled: true
            storageClass: "local-path"
            accessMode: ReadWriteOnce
            size: 20Gi

          media:
            enabled: true
            type: hostPath
            # ❗️ IMPORTANT: Change this to the absolute path of your media folder!
            hostPath: "/home/sagi/sagi"
            accessMode: ReadWriteOnce
            size: 100Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
