apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USERNAME/YOUR_REPO.git' # <--- Replace with your repository URL!
    targetRevision: HEAD
    path: charts/plex-wrapper
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
