# These values will be passed to the subchart named pms-docker
pms-docker:
  image:
    tag: plexpass # or any other version you choose

  timezone: "Asia/Jerusalem"

  service:
    type: LoadBalancer # Change to NodePort if you don't have a Load Balancer
    port: 32400
    
  podAnnotations:
    "container.apparmor.security.beta.kubernetes.io/plex-media-server": "unconfined"

  persistence:
    config:
      enabled: true
      storageClass: "local-path" # The default in k3s
      accessMode: ReadWriteOnce
      size: 20Gi

    media:
      enabled: true
      type: hostPath # Direct mapping to a folder on the server
      hostPath: "/home/sagi/sagi" # <--- Change this to your actual media path!
      accessMode: ReadWriteOnce
      size: 100Gi # A symbolic size
